export const now = {
  updated: "2026-04-20",
  location: "Bekasi, ID (UTC+7)",
  lines: [
    "# now.txt",
    "",
    "updated  : 2026-04-20",
    "location : Bekasi, ID (UTC+7)",
    "status   : heads-down on Pulse",
    "",
    "## this week",
    "- Pulse: outbox-relayer reconnect bug, auth healthcheck cleanup",
    "- Pulse: e-commerce aggregator architecture draft",
    "- Aenoxa: PT formation paperwork w/ Suryadi",
    "- Landing generator: first paid tier pricing study",
    "",
    "## this month",
    "- Ship native Android wrapper v1.2 with USB printer support",
    "- First Aenoxa AI workflows engagement (scoping)",
    "- Publish writeup: 'Why we killed our HTTPS bridge for a Kotlin plugin'",
    "",
    "## reading",
    "- Designing Data-Intensive Applications (reread)",
    "- High Output Management, Andrew Grove",
    "",
    "## listening",
    "- mpv + yt-dlp, late-night instrumental sets",
    "",
    "-- toper",
  ],
};
